using System.Collections.Generic;
using System.Runtime.Serialization;

namespace CarDeliveryNetwork.Api.Data
{
    /// <summary>
    /// A Car Delivery Network FoundJob entity.
    /// </summary>
    public class FoundJob : ApiEntityBase<FoundJob>
    {
        /// <summary>
        /// A unique identifier for this job, generated by the client system.
        /// </summary>
        public virtual string LoadId { get; set; }

        /// <summary>
        /// The job's unique job number generated by Car Delivery Network.
        /// </summary>
        public virtual string JobNumber { get; set; }
    }

    /// <summary>
    /// A collection of Car Delivery Network Job job entities.
    /// </summary>
    [CollectionDataContract]
    public class FoundJobs : ApiEntityCollectionBase<FoundJob, FoundJobs>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CarDeliveryNetwork.Api.Data.FoundJobs"/> class
        /// that is empty and has the default initial capacity.
        /// </summary>
        public FoundJobs() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="CarDeliveryNetwork.Api.Data.FoundJobs"/> class
        /// that is empty and has the specified initial capacity.
        /// </summary>
        /// <param name="capacity">The number of elements that the new list can initially store.</param>
        public FoundJobs(int capacity) : base(capacity) { }

        /// <summary>
        /// Initializes a new instance of the <see cref="CarDeliveryNetwork.Api.Data.FoundJobs"/> class
        /// that contains elements copied from the specified collection and has sufficient
        /// capacity to accommodate the number of elements copied.
        /// </summary>
        /// <param name="foundJobs">The collection of jobs whose elements are copied to the new collection.</param>
        public FoundJobs(IEnumerable<FoundJob> foundJobs) : base(foundJobs) { }
    }
}