//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyCompany("Car Delivery Network Ltd.")]
[assembly: System.Reflection.AssemblyProduct("Car Delivery Network")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Car Delivery Network Ltd. 2014")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.1.0")]
[assembly: System.Reflection.AssemblyVersion("0.0.1.0")]


