using System;
using System.Linq;
using CarDeliveryNetwork.Api.ClientProxy;
using CarDeliveryNetwork.Api.Data;
using log4net;

namespace CdnLink
{
    public class CdnLink
    {
        private static readonly ILog Log = LogManager.GetLogger(typeof(CdnLink));

        public string ConnectionString { get; private set; }
        public ICdnApi Api { get; private set; }
        public ICdnFtpBox FtpBox { get; private set; }

        public CdnLink(
            string connectionString,
            ICdnApi api,
            ICdnFtpBox ftpBox)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString string cannot be null or empty");

            ConnectionString = connectionString;
            Api = api;
            FtpBox = ftpBox;
        }

        public int Send()
        {
            var db = new CdnLinkDataContext(ConnectionString);
            var sends = from send in db.CdnSends
                        where send.Status == (int)CdnSend.SendStatus.Queued
                        select send;

            var sendCount = sends.Count();
            Log.InfoFormat("Send: Processing {0} records(s).", sendCount);
            if (sendCount > 0)
            {
                foreach (var send in sends)
                    try
                    {
                        // Set the send as in process
                        send.ProcessingDate = DateTime.Now;
                        send.Status = (int)CdnSend.SendStatus.Processing;
                        db.SubmitChanges();

                        switch (send.Action)
                        {
                            case null:
                            case (int)CdnSend.SendAction.Create:
                                Api.CreateJob(send.CdnSendLoad.ToCdnJob());
                                break;

                            case (int)CdnSend.SendAction.Cancel:
                                Api.CancelJob(send.LoadId, null);
                                break;
                           
                            default:
                                throw new ArgumentException(string.Format("Action {0} is not supported", send.Action), "Action");
                        }

                        // Set the send as sent
                        send.SentDate = DateTime.Now;
                        send.Status = (int)CdnSend.SendStatus.Sent;
                        db.SubmitChanges();
                    }
                    catch (HttpResourceFaultException ex)
                    {
                        send.SetAsError(ex.Message, ex.StatusCode.ToString());
                        db.SubmitChanges();
                        throw;
                    }
                    catch (Exception ex)
                    {
                        send.SetAsError(ex.Message);
                        db.SubmitChanges();
                        throw;
                    }
            }
            return sendCount;
        }

        public int Receive()
        {
            var files = FtpBox.GetFileList();
            var fileCount = files.Count;
            Log.InfoFormat("Receive: Processing {0} file(s).", fileCount);
            if (fileCount > 0)
            {
                var db = new CdnLinkDataContext(ConnectionString);
                var index = 1;
                foreach (var file in files.ToArray())
                {
                    // If we haven't already processed this file
                    var seenFile = db.CdnReceivedFtpFiles.Count(f => f.Filename.Contains(file)) > 0;
                    if (!seenFile)
                    {
                        Console.WriteLine("Processing file {0} of {1}", index++, fileCount);
                        var json = FtpBox.GetFileContents(file);
                        var job = Job.FromString(json);
                        if (job == null)
                            throw new Exception(string.Format("Json produced a null job: {0}", json));

                        // Check that this isn't a test hook message generated by CDN
                        if (job.Id != -1)
                        {
                            var receivedFile = new CdnReceivedFtpFile
                            {
                                Filename = file,
                                JsonMessage = json
                            };

                            var receive = new CdnReceive
                            {
                                FetchedDate = DateTime.Now,
                                Status = (int) CdnReceive.ReceiveStatus.Processing
                            };

                            receivedFile.CdnReceive = receive;

                            db.CdnReceivedFtpFiles.InsertOnSubmit(receivedFile);
                            db.SubmitChanges();

                            try
                            {
                                Log.Debug("Receive: Setting the received load");
                                receivedFile.CdnReceivedLoads.Add(new CdnReceivedLoad(job));
                                Log.Debug("Receive: Setting the status to queued");
                                receive.Status = (int) CdnReceive.ReceiveStatus.Queued;
                                Log.Debug("Receive: Submittig ...");
                                db.SubmitChanges();
                                Log.Debug("Receive: Done.");
                            }
                            catch (Exception ex)
                            {
                                Log.Debug("Receive: Error:  Setting error info ...");
                                receive.SetAsError(ex.Message);
                                Log.Debug("Receive: Error:  Saving error info ...");
                                db.SubmitChanges();
                                Log.Debug("Receive: Re-throwing.");
                                throw;
                            }
                        }
                    }

                    // Delete file from FTP server
                    Log.DebugFormat("Receive: Deleting FTP file: {0} ...", file);
                    FtpBox.DeleteFile(file);
                    Log.Debug("Receive: Done.");
                }
            }
            return fileCount;
        }
    }
}
