<?xml version="1.0" encoding="utf-8"?><Database Name="CdnLink" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=CdnLink;User ID=thedbusername" SettingsObjectName="CdnLink.Settings" SettingsPropertyName="CDNLINK_CONNECTIONSTRING" Provider="System.Data.SqlClient" />
</Database>